export default [
    { name: 'powerchord', postfix: '5', intervals: [7, 5] },
    { name: 'major', postfix: '', intervals: [4, 3, 5] },
    { name: 'minor', postfix: 'm', intervals: [3, 4, 5] },
    { name: 'augmented', postfix: 'aug', intervals: [4, 4, 4] },
    { name: 'diminished', postfix: 'dim', intervals: [3, 3, 6] },
    { name: 'suspended', postfix: 'sus2', intervals: [2, 5, 5] },
    { name: 'suspended', postfix: 'sus4', intervals: [5, 2, 5] },
    { name: '7major(short)', postfix: '7maj', intervals: [7, 4, 1] },
    { name: '7(short)', postfix: '7', intervals: [7, 3, 2] },
    { name: '6major', postfix: '6maj', intervals: [4, 3, 2, 3] },
    { name: '6minor', postfix: '6min', intervals: [3, 4, 2, 3] },
    { name: '7diminished', postfix: '7dim', intervals: [3, 3, 3, 3] },
    { name: '7major', postfix: '7maj', intervals: [4, 3, 4, 1] },
    { name: '7minor', postfix: '7min', intervals: [3, 4, 3, 2] },
    { name: '7augmented', postfix: '7aug', intervals: [4, 4, 2, 2] },
    { name: '7half-diminished', postfix: '7hdim', intervals: [3, 3, 4, 2] },
    { name: '7dominant', postfix: '7dom', intervals: [4, 3, 3, 2] },
    { name: '7minor-major', postfix: '7minmaj', intervals: [3, 4, 4, 1] },
    { name: '7augmented-major', postfix: '7augmaj', intervals: [4, 4, 3, 1] },
    { name: '9add', postfix: '9add', intervals: [2, 2, 3, 5] },
    { name: '9', postfix: '9', intervals: [2, 2, 3, 3, 2] },
    { name: '9minor', postfix: '9min', intervals: [2, 1, 4, 3, 2] },
    { name: '9major', postfix: '9maj', intervals: [2, 2, 3, 4, 1] },
    { name: 'b9', postfix: '9-', intervals: [1, 3, 3, 3, 2] },
    { name: '#9', postfix: '9+', intervals: [3, 1, 3, 3, 2] },
    { name: '11(short)', postfix: '11', intervals: [4, 1, 2, 3, 2] },
    { name: '11', postfix: '11', intervals: [2, 2, 1, 2, 3, 2] },
    { name: '13(short)', postfix: '13', intervals: [4, 3, 2, 1, 2] },
    { name: '13', postfix: '13', intervals: [2, 2, 1, 2, 2, 1, 2] },
];
